### ISSUE TITLE
Google+ makes request to Yandex

### ISSUE THREAD

**Issue by Matvik** [assayer-pro/yii2-social-likes#1]
There is some request to Yandex when using Google+ share option. This is the problem due to ukrainian restrictions (yandex is now banned in Ukraine), so page is freezing. Can you remove this Yandex request? Thank`s.

**Comment by serge-larin** [comment]
Sorry, but yii2-social-likes only wrapper for http://sapegin.github.io/social-likes/.
social-likes using share.yandex.ru/gpp.xml for show Google+ like counter, see https://github.com/sapegin/social-likes/blob/master/src/social-likes.js#L118 (line 118).
Please write your request to the author http://sapegin.github.io/social-likes/
It is possible as a temporary solution to turn off counters.
`SocialLikes::widget([
... 'showCounters' => false, ...
])`

**Comment by Matvik** [comment]
Ok, thanks!
